---
- name: "Install dependencies"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Install key docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable 

- name: Install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Check docker status
  service:
    name: docker
    state: started
    enabled: yes